deviceName=Nexus 5
platformName=Android
avd=Nexus_5_API_35
automationName=UiAutomator2
appWaitActivity=activity-to-wait-for
fullReset=true
remoteURL=http://127.0.0.1:4723/wd/hub
app=src/main/resources/apps/YandexMarket.apk