automationName=UiAutomator2
appWaitActivity=ru.yandex.market.ui.splash.MarketSplashActivity
fullReset=true
remoteURL=http://127.0.0.1:port/wd/hub
chromedriverExecutable=/src/main/resources/web/drivers/chromedriver-win64/chromedriver.exe
app=src/main/resources/apps/YandexMarket.apk