version: "3"

services:
  selenoid:
    build: selenoid
    container_name: selenoid
    ports:
      - "4444:4444"
    network_mode: bridge
    #    networks:
    #      - selenoid_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    container_name: selenoid-ui
    ports:
      - "90:8080"
    network_mode: bridge
    #    networks:
    #      - selenoid_net
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
#  tests:
#    container_name: tests
#    build: .
#    network_mode: bridge
#    depends_on:
#      - selenoid
#      - selenoid-ui
#
networks:
  selenoid_net:
    driver: bridge